// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ABackTop: typeof import("ant-design-vue/es")["BackTop"];
    AButton: typeof import("ant-design-vue/es")["Button"];
    AConfigProvider: typeof import("ant-design-vue/es")["ConfigProvider"];
    ALayout: typeof import("ant-design-vue/es")["Layout"];
    ALayoutContent: typeof import("ant-design-vue/es")["LayoutContent"];
    ALayoutFooter: typeof import("ant-design-vue/es")["LayoutFooter"];
    ALayoutHeader: typeof import("ant-design-vue/es")["LayoutHeader"];
    ALayoutSider: typeof import("ant-design-vue/es")["LayoutSider"];
    AMenu: typeof import("ant-design-vue/es")["Menu"];
    AMenuItem: typeof import("ant-design-vue/es")["MenuItem"];
    ASpace: typeof import("ant-design-vue/es")["Space"];
    ASubMenu: typeof import("ant-design-vue/es")["SubMenu"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"];
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"];
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"];
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"];
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TheWelcome: typeof import("./src/components/TheWelcome.vue")["default"];
    WelcomeItem: typeof import("./src/components/WelcomeItem.vue")["default"];
  }
}
